?start: commands*
?commands: set | require | call | func | fi | ret

?atom: CNAME | INTEGER | STRING | dict
?expr: call -> call_on_expr
    | member
    | atom
    | expr "+" expr -> plus
    | expr "-" expr -> sub
    | expr "/" expr -> div
    | expr "*" expr -> mul

arg_names: CNAME ("," CNAME)*
block: commands*
?member: expr "." CNAME
    
dict_key: CNAME ":" expr
dict: "{" dict_key ("," dict_key)* "}"

require: "require" STRING "as" CNAME
set: "local" CNAME "=" expr
call: expr "("(expr ("," expr)*)?")"
func: "fn" CNAME "{" commands* "}" | "fn" CNAME "("")" "{" commands* "}"
    | "fn" CNAME "(" arg_names ")" "{" commands* "}" -> func_args
ret: "return" expr

condition: expr
          | condition "==" condition -> equ
          | condition "!=" condition -> nequ
          | condition ">" condition -> gt
          | condition "<" condition -> lt
          | condition ">=" condition -> gte
          | condition "<=" condition -> lte

?logic_condition: condition 
    | logic_condition "and" condition -> andc
    | logic_condition "or" condition -> orc

fi: "if" logic_condition "{" block "}" (elfi | elsf)?
elfi: "elseif" logic_condition "{" block "}" (elfi | elsf)?
elsf: "else" "{" block "}"

INTEGER: "-"NUMBER | "+"NUMBER | NUMBER
%import common.CNAME
%import common.NUMBER -> NUMBER
%import common.ESCAPED_STRING -> STRING
%import common.WS

%ignore WS